kind: pipeline
type: docker
name: tests

steps:
- name: unit
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
  - go mod download
  - go test -coverprofile=coverage.out -covermode=count ./...
  - go tool cover -func=coverage.out | grep total

- name: race
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
  - go mod download
  - go test -race ./...

volumes:
- name: cache
  temp: {}
